### ISSUE TITLE
Possible weird behavior when a radio isn't checked in before being checked out

### ISSUE THREAD

**Issue by flwyd** [burningmantech/ranger-clubhouse-web#1413]
While WESLing, I noticed several cases of the Control 1 Monitor showing a different Ranger's handle from the person who verbally identified on the call.  I investigated one example of this on Saturday at roughly 18:00.

* Asset #7098 was shown as transmitting
* Control 1 Monitor showed this radio as `Majorsquirrel` but the voice on the radio identified as `Mufasa`
* I looked up #7098 in the Clubhouse and it showed that it was checked out to `Majorsquirrel` on Friday at 17:54 with no check in time
* At 19:58 a brief asset history record was created for asset #7098 assigned to `Mufasa` before assigning it to a different Ranger.  The same HQ Window operator had checked `Mufasa` in 14 minutes earlier; I don't know if they looked up `Mufasa` to create an audit trail or if they navigated to Mufasa for some other reason and got confused about who was checking out a radio.

Hypothesis #1: Someone tried to check out asset #7098 to `Mufasa` but it didn't create an asset history record because it was already checked out?  
Hypothesis #2: Somehow dumb luck coincided an HQ Window person handing over a radio without checking it out _and_ that radio wasn't properly checked in the day before?

We should do some testing with various radio checkout scenarios (e.g. check out a radio that wasn't checked in, checking in a radio that wasn't checked out) and make sure the right DB records get created and/or HQ Window operators are adequately informed about problems.

We might also think about highlighting (on the HQ Window view of a person's page) a Ranger who's checked in to shift but doesn't have a radio checked out.  This would help catch operator errors in handing over a radio without checking it out, and would also help folks who end up with a radio before HQ Window operations are running (e.g. DPW Rangers, SITE Team) and catch their asset number later so that it can show up on the Control 1 Monitor.  (As it was, people like `Crow` frequently showed up as *Unknown* because the Clubhouse didn't have an asset history record for their radios.)

**Comment by mikeburg** [comment]
During the debrief with both the HQ Window workers, and with the Timesheet Wrangler strike team, two things can be concluded:

1. Playa & pandemic brain fog was full force  this event. Workers failed on numerous  occasions to perform all the steps for checking in and out a Ranger to/from a shift. Meal pogs were not offered, basic timesheet entry corrections were mishandled (e.g., workers ended a shift  and started a new one to correct a position instead of using the 'correct position' feature), a rampant misunderstand of being able to work a shift regardless if you started late or were not signed up, and most relevant to this github issue, radios were not retrieved and/or not marked as checked out.  

2. The HQ Window interface should be redesigned to be a 'lock-step' wizard interface - i.e., the interface needs to walk the worker thru each step explicitly instead relying on the worker to scroll thru the page to perform all necessary tasks. A checklist might be ideal to present to the worker as well.

I  strongly believe an underlying database or code issue does not exist. This issue is really about pilot error, workers being out of practice, the cognitive impairment the playa environment induces, and the mental stress most folks have experienced during these last couple of years.  

Closing this issue out.
