### ISSUE TITLE
New Maintenance Feature: Bulk Convert Alphas

### ISSUE THREAD

**Issue by rangerthreepio** [burningmantech/ranger-clubhouse-web#265]
We currently have to convert trained prospectives to alphas each by each, instead of using a bulk "convert all trained prospectives to alpha" button in maintenance. Lets fix that.

**Comment by wsanchez** [comment]
Confirm desired workflow with Mentor Cadre.

**Comment by techxorcist** [comment]
Requests bulk method for changing from Trained Prospective to Alpha and confirmation with Mentors about desired workflow.
Yes, just Prospective>Alpha under conditions: If they Status=Propspective, and Trained=Yes, then Bulk Button (available to Mentor Cadre+Intake Manager) converts all people with that status to Alpha and reports handles and errors.
Still need to confirm workflow with 2Step+Cadre. He's used to doing this one by one and this is my suggestion to speed that up for him.

**Comment by techxorcist** [comment]
2Step: As long as your query extracts those two parameters it should work fine.  It's something that has to be done after the previous training's are done and the trainers have updated the Flagging System with their data/ratings.  It's best if we do the update since we need to know how many Alpha slots to create in the Clubhouse.  Those are proportioned across the six Alpha Shifts so that those training later in the year have equal shot at all the shifts.

This reads to me as clearly defined for whenever it can be worked on but let me know if more finding out is in order.

**Comment by mikeburg** [comment]
Implemented! Please test!

**Comment by mikeburg** [comment]
Appears to be working. Closing out.
