### ISSUE TITLE
Multiple Enrollments code may not be working as intended

### ISSUE THREAD

**Issue by rangerthreepio** [burningmantech/ranger-clubhouse-web#268]
I have a note that unusual multiple enrollments existed for Trekker, Hooper, Mindset, and Sub-Diver this year. Sadly I didn't take closer notes, aside from to investigate the code and those four names.

**Comment by mikeburg** [comment]
This has been resolved.  The four people listed, along with Turbine, were able to sign up for multiple trainings due to a Clubhouse bug. The bug allowed people to sign up for one part of a two part session, and then sign up for a full session. The loophole was closed around July 22nd.  Closing this out.
