### ISSUE TITLE
Timesheet by Position report

### ISSUE THREAD

**Issue by techxorcist** [burningmantech/ranger-clubhouse-web#272]
Submitted by email from Nobooty:

My position is:
I would like to request a new clubhouse report "Timesheet by Position" which would be just about like it sounds. That being, the ability to select one or more Positions and get a chronological list of timesheet entries that match.

My interest is:
- When doing timesheet corrections it's useful to find out when everyone else in a position signed off. E.g. burn perimeter, long running GD calls, Field Echelon.
- In timesheet corrections sometimes Rangers can't remember the exact handle of their partner for the shift but can get close.
- Tracking down IMS incidents when Rangers on scene get mis-reported or when Operators can't understand the callsign and log something close. 
- To get real numbers of Rangers on a shift rather than estimated numbers based on the 'Schedule by Position' report.
- To find out how many unscheduled sign-ins are happening.
- To find out which shifts get fully scheduled but don't get fully staffed. This may need a historical option as well.

Priority - useful for [late September 2019] for timesheet corrections, then not useful until staffing estimates in the spring.

**Comment by Nobooty** [comment]
Another possible use: Track/log all Rangers who actually worked a specific position. If 'show emails' was an option (for those with proper permissions) then things like sending an email to everyone who worked a particular Position becomes easier. With an export to CSV this kind of filtering can be done in a spreadsheet rather than built into the report.

**Comment by mikeburg** [comment]
> Another possible use: Track/log all Rangers who actually worked a specific position. If 'show emails' was an option (for those with proper permissions) then things like sending an email to everyone who worked a particular Position becomes easier. With an export to CSV this kind of filtering can be done in a spreadsheet rather than built into the report.

@Nobooty This is already available on the Reports > People > People By Special Teams page. The report is only a summary of total hours worked in the selected positions.. Email addresses are shown to users who have the appropriate permissions. And yes, a CSV export is available.

**Comment by Nobooty** [comment]
@mikeburg The PbST report doesn't break it down by position if more than one is selected, and you lose the shift date-time data, but otherwise, yes, that is apparently exactly what I think I was thinking. I can't remember if I had a different vision of the report or just was forgetting about that one.

**Comment by mikeburg** [comment]
The report has been created! Reports > Timesheets > Timesheet By Position

**Comment by mikeburg** [comment]
Report has been live for almost 4 months and no additional suggestions received. Closing out
