### ISSUE TITLE
Timesheet entries should be related to shifts (most of the time)

### ISSUE THREAD

**Issue by wsanchez** [burningmantech/ranger-clubhouse-web#290]
Timesheet entries should be related to shifts (most of the time).

Which is to say that when a Ranger signs in at HQ for a first shift (and I suspect most other shifts), that sign-in should be associated with the coming (or perhaps current, if you are signing in late) shift.

This would make it a lot easier to write code that detect when someone signs into a shift late, or stays beyond the shift.  When a Ranger signs in late (by more than some "normal" margin), we could even have HQ log a note about why.

That said, we do have some ad-hoc sign-ins that would not be associated with any scheduled shift.  Council Managers are an example, but also some roles like 007, or maybe ROC Manager, and so on.  Being able to easily query for these is also useful, and auditing how that is being used is interesting.

**Comment by mikeburg** [comment]
Timesheet entry and shift association would be fairly trivial to implement with the HQ WIndow Interface. The UI already has a predictive shift feature that presents the  HQ worker with the option to check the person into the position of the shift they signed up for. A slot_id column could be added timesheet table to associate an entry with a shift. The UI would start the shift using the shift/slot id instead of a selected position.

When the worker selects a position instead of a shift to sign into, the UI would pop up a dialog asking for an explanation.

Burn nights might be problematic. We encourage Rangers who worked a Burn Perimeter to come back to HQ, sign out of the B.P.  shift, and complete a shortened Dirt shift. The reason is B.P. shifts are typically 3 to 4 hours in length, and are (usually) not eligible for a full meal pog. Also Saturday and Sunday nights are chronically understaffed, and Khaki really could use the additional bodies to cover the city. For burn nights, the UI probably should skip asking for an explanation on why the Ranger is signing into a Dirt position where the shift is half done.

**Comment by mikeburg** [comment]
Shift sign in (Timesheet::store) will attempt to associate a timesheet entry with a shift.

**Comment by mikeburg** [comment]
Appears to be working. Was tested during O.N.E. 2. Closing out.

**Comment by flwyd** [comment]
If someone works a double do we want to have HQ sign them out from shift 1 and back in to shift 2?  Or is it okay if a timesheet entry is just associated with _a_ shift that the person worked, not _all_ of them?
