### ISSUE TITLE
Acceptance Tests Fail

### ISSUE THREAD

**Issue by flwyd** [burningmantech/ranger-clubhouse-web#3]
The `redirect to /login` acceptance test fails because `Ember.$(...).compose is not a function`.
The `admin/positions` and `invalid login` acceptance tests fail because `this.session.user` is null in MeRoute, maybe due to some fixture loading issue?
The `invalid login` test fails with a timeout, I'm not sure why.

**Comment by mikeburg** [comment]
Huh, not seeing the 'Ember.$()' problem on my end. The test was hanging due to ember-simple-auth-token creating a (unnecessary) timer to refresh the JWT token. The addon changed since the login test was last working. Before the addon would not create a timer if the refresh API end point was not given. The current version creates a timer if the token has an expiry attribute regardless if the refresh end point is given or not. tokenExpirationInvalidateSession configuration flag set to false prevents the timer from being created, and allows the test to pass without timing out.

Regardless, both tests are passing now.

Leaving this issue open in case something else crops up...

**Comment by mikeburg** [comment]
No other problems seen on this issue. Closing out.
