### ISSUE TITLE
Salesforce Import "Show All Records" fails

### ISSUE THREAD

**Issue by rangerthreepio** [burningmantech/ranger-clubhouse-web#53]
![6](https://user-images.githubusercontent.com/45806097/54233587-734cb400-44ca-11e9-9b4a-8f479da1efd2.png)

**Comment by mikeburg** [comment]
Safety Phil says this is a known bug with SF.

**Comment by plapsley** [comment]
This is a known bug that predates CH2.  The issue is that Salesforce returns chunks of 1000 records at a time, so if you make a query (such as "show all") to Salesforce that results in more than 1000 records, it gives you back the first thousand and sets unfinished bit so you know to request the next thousand.  The Clubhouse code doesn't handle this.  The good news is, this doesn't impact our operations, because we should never been importing more than a few hundred accounts at a time.  It only shows up if you check the "show all" box, which isn't used operationally.  Would be nice to fix, but low priority.

**Comment by rangerthreepio** [comment]
Thanks, I am remembering this now. I am finding other, more pressing bugs.
Will flag this as super low priority.

**Comment by mikeburg** [comment]
Fixed. And the CH2 import page include a comment about only the first 1,000 records are shown.

**Comment by rangerthreepio** [comment]
appears to be working
