### ISSUE TITLE
TWII List to persist for 3 years from upload

### ISSUE THREAD

**Issue by rangerthreepio** [burningmantech/ranger-clubhouse-web#83]
Adding feature request per Tool/Council decision 3/19/19 which states that the TWII list used in the handle checker shall include the last three TWII handle lists, meaning each new list added should persist in the reservedcallsign.php for three years, and then be removed. Note that the list is largely overlapping each year. @flwyd has more information about that arcane section of code, shrouded in mystery, layered in enigma, and cursed with the hatred of a thousand damned souls.

**Comment by rangerthreepio** [comment]
Please note the VCs do not need this for the 2019 event, but will for the 2020 event.

**Comment by wsanchez** [comment]
My suggestion here is that when a name is no longer in TWII that it remain on our list for a few years, on the assumption that having been on TWII, the name is probably relevant for some time, and to reduce the amount of manual review of such names.

**Comment by flwyd** [comment]
Fixed by https://github.com/burningmantech/ranger-clubhouse-api/pull/74

The update process can now be pretty dumb: add the new year as a big array (minus anything which really obviously shouldn't be on the VIP list, like Khaki[1]) and reference that in the `twiiVips` function.  If there are more than three years' worth of arrays, remove the oldest year's array.

[1] Khaki is on a separate list of reserved handles.
